version: "3.8"

services:
  employeeapp:
    image: employeeapp:latest
    container_name: employeeapp_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7070:80"
    restart: unless-stopped
